### ISSUE TITLE
ModuleNotFoundError: No module named 'uvicorn'

### ISSUE THREAD

**Issue by rafstahelin** [D8-Dreambooth/stable-diffusion-plus#1]
Does anyone know how to fix this?

ModuleNotFoundError: No module named 'uvicorn'?

Also  error: Microsoft Visual C++ 14.0 or greater is necessary, but I have Visual Studio C++ 17
Can anyone help?

**Comment by Phando** [comment]
`pip install uvicorn `
will get you one step closer.

What might be needed is:
`pip install -r requirements.txt`

I was getting the following error so I moved the transformers version in requirements.txt to 4.25.1
Still seeing issues...
